# Default values for vault.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# ArgoCD will be injecting these common labels
# during deployment of this Helm Chart.
# These common labels will be applied to all the resources
# commonLabels: {}

replicaCount: 3

vaultMetrics:
  enabled: true
  unauthenticatedAccess: true
  prometheusRetentionTime: 30s

# Vault TLS related configuration
tls: {}
  # The name of the secret that contains a TLS server certificate, key, and the corresponding CA certificate. The secret must be in the kubernetes.io/tls type secret keys + ca.crt key format.
  # If the attribute is set, the operator uses the certificate already set in the secret, otherwise it generates a new one.
  # The ca.crt key is mandatory, otherwise the Bank-Vaults components can’t verify the Vault server certificate.
  # secretName: ""
  # CANamespaces define a list of namespaces where the generated CA certificate for Vault should be distributed, use ["*"] for all namespaces. default: []
  # caNamespaces: ["*"]

# Allows creating policies in Vault.
# See https://www.vaultproject.io/docs/concepts/policies.html for more information.
# Check `policies` field in https://github.com/bank-vaults/bank-vaults/blob/main/vault-config.yml
# for documentation on how this field's structure should look like
vaultPolicies: []
  # - name: allow_secrets
  #   rules: path "secret/*" {
  #       capabilities = ["create", "read", "update", "delete", "list"]
  #     }

# Allows configuring Auth Methods in Vault.
# See https://www.vaultproject.io/docs/auth/ for more information.
# Check `auth` field in https://github.com/bank-vaults/bank-vaults/blob/main/vault-config.yml
# for documentation on how this field's structure should look like
vaultAuthMethods: []
  # - type: kubernetes
  #   path: kubernetes
  #   description: "Kubernetes authentication method"
  #   config:
  #     disable_iss_validation: true
  #     kubernetes_host: "https://kubernetes.default.svc.cluster.local"
  #     kubernetes_ca_cert: |
  #       -----BEGIN CERTIFICATE-----
  #       abcdefghijklmnopqrstuvwxyz
  #       -----END CERTIFICATE-------
  #   roles:
  #     - name: default
  #       bound_service_account_names: ["default"]
  #       bound_service_account_namespaces: ["default"]
  #       policies: allow_secrets
  #       ttl: 1h

# Allows configuring Secrets Engines in Vault (KV, Database and SSH is tested,
# but the config is free form so probably more is supported).
# See https://www.vaultproject.io/docs/secrets/index.html for more information.
# Check `secrets` field in https://github.com/bank-vaults/bank-vaults/blob/main/vault-config.yml
# for documentation on how this field's structure should look like
vaultSecretEngines: []
  # # This plugin stores arbitrary secrets within the configured physical storage for Vault.
  # # See https://www.vaultproject.io/docs/secrets/kv/ for
  # # more information.
  # - path: secret
  #   description: "Generic secret storage"
  #   type: kv
  #   options:
  #     version: 2

# Allows configuring Audit Devices in Vault (File, Syslog, Socket).
# See https://www.vaultproject.io/docs/audit/ for more information.
# Check `audit` field in https://github.com/bank-vaults/bank-vaults/blob/main/vault-config.yml
# for documentation on how this field's structure should look like
vaultAuditDevices: []
  # - type: file
  #   description: "File based audit logging device to send logs to standard output (stdout)"
  #   options:
  #     file_path: stdout
  # - type: file
  #   description: "File based audit logging device"
  #   options:
  #     file_path: /tmp/vault.log

# Vault Envs configuration
vaultEnvsConfig: []
  # - name: VAULT_LOG_LEVEL
  #   value: info

# Vault unseal configuration
unsealConfig:
  secretShares: 5
  secretThreshold: 3

imagePullSecrets: []
  # - name: secretName
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP

ingresses: []
  # - className: ""
  #   annotations: {}
  #     # kubernetes.io/ingress.class: nginx
  #     # kubernetes.io/tls-acme: "true"
  #   hosts:
  #     - host: chart-example.local
  #       paths:
  #         - path: /
  #           pathType: ImplementationSpecific
  #   tls: []
  #   #  - secretName: chart-example-tls
  #   #    hosts:
  #   #      - chart-example.local

# Everything pertaining to the Vault Pods
vault:
  apiPort: 8200
  clusterPort: 8201
  image:
    repository: hashicorp/vault
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  persistence:
    storageClass: ""
    size: 1Gi

# Vault Pods , Services and TLS Secret annotations
vaultAnnotations: {}
  # type/instance: vault

# Vault Configurer Pods and Services annotations
vaultConfigurerAnnotations: {}
  # type/instance: vaultconfigurer

velero:
  enabled: true

# NodeSelector is Kubernetes NodeSelector definition that should be applied to all Vault Pods. default: {}
nodeSelector: {}

# If specified, the Vault Pod’s tolerations.
tolerations: []

# Affinity is a group of affinity scheduling rules applied to all Vault Pods. default: {}
affinity: {}
