# This binding allows the deployed Vault instance to authenticate clients
# through Kubernetes ServiceAccounts (if configured so).

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "vault.labels" $ | nindent 4 }}
  name: {{ include "vault.authDelegatorClusterRoleBindingName" $ }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: {{ include "vault.serviceAccountName" $ }}
  namespace: {{ .Release.Namespace }}
