apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "vault.labels" $ | nindent 4 }}
  name: {{ include "vault.fullname" $ }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vault.fullname" $ }}
subjects:
- kind: ServiceAccount
  name: {{ include "vault.serviceAccountName" $ }}
  namespace: {{ .Release.Namespace }}
